apiVersion: apps/v1
kind: Deployment

metadata:
  name: seclock-deployment
  namespace: seclock

spec:
  replicas: 2

  selector:
    matchLabels:
      app: seclock

  template:
    metadata:
      labels:
        app: seclock

    spec:
      containers:
        - name: seclock

          image: 425951817568.dkr.ecr.us-east-1.amazonaws.com/seclock:14

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
